/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProfessionalsIdRouteImport } from './routes/professionals.$id'
import { Route as CampaignsNewRouteImport } from './routes/campaigns.new'

const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfessionalsIdRoute = ProfessionalsIdRouteImport.update({
  id: '/professionals/$id',
  path: '/professionals/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsNewRoute = CampaignsNewRouteImport.update({
  id: '/campaigns/new',
  path: '/campaigns/new',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/marketplace': typeof MarketplaceRoute
  '/messages': typeof MessagesRoute
  '/campaigns/new': typeof CampaignsNewRoute
  '/professionals/$id': typeof ProfessionalsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/marketplace': typeof MarketplaceRoute
  '/messages': typeof MessagesRoute
  '/campaigns/new': typeof CampaignsNewRoute
  '/professionals/$id': typeof ProfessionalsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/marketplace': typeof MarketplaceRoute
  '/messages': typeof MessagesRoute
  '/campaigns/new': typeof CampaignsNewRoute
  '/professionals/$id': typeof ProfessionalsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/marketplace'
    | '/messages'
    | '/campaigns/new'
    | '/professionals/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/marketplace'
    | '/messages'
    | '/campaigns/new'
    | '/professionals/$id'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/marketplace'
    | '/messages'
    | '/campaigns/new'
    | '/professionals/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  MarketplaceRoute: typeof MarketplaceRoute
  MessagesRoute: typeof MessagesRoute
  CampaignsNewRoute: typeof CampaignsNewRoute
  ProfessionalsIdRoute: typeof ProfessionalsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/professionals/$id': {
      id: '/professionals/$id'
      path: '/professionals/$id'
      fullPath: '/professionals/$id'
      preLoaderRoute: typeof ProfessionalsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/new': {
      id: '/campaigns/new'
      path: '/campaigns/new'
      fullPath: '/campaigns/new'
      preLoaderRoute: typeof CampaignsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  MarketplaceRoute: MarketplaceRoute,
  MessagesRoute: MessagesRoute,
  CampaignsNewRoute: CampaignsNewRoute,
  ProfessionalsIdRoute: ProfessionalsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
